language: python
python:
  - "3.6"
before_install:
 - curl https://sh.rustup.rs -sSf -o rustup.sh
 - sh rustup.sh -y
 - export PATH=$PATH:~/.cargo/bin
 - rustc --version
script: ./build.sh
notifications:
  email: false
